[package]
name = "bevy_background"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
wgpu = "0.12"

bevy_mod_debugdump = "0.4.0"